version: "3.3"

services:
  redis-db:
    image: redis/redis-stack-server
    container_name: "redis-db"
    restart: always    
    ports:
      - "6379:6379"
    volumes:
      - ./local-data:/data

  app:
    build: .    
    container_name: "app"
    restart: always    
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - redis-db
      
